#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/oldschool_with_arduino.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/fullscreen.jar:$APPDIR/lib/arduino.jar:$APPDIR/lib/fullscreen.jar:$APPDIR/lib/xml.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar" oldschool_with_arduino
